let shopItemsData = [
  {
    id: "apple",
    name: "Apple",
    price: 35,
    desc: "This is a fresh apple harvested just today. Grub yours fast.",
    img: "Images/apple.JPG",
  },
  {
    id: "wheat",
    name: "Wheat",
    price: 50,
    desc: "This is a fresh wheat harvested just today. Grub yours fast.",
    img: "Images/wheat.JPG",
  },
  {
    id: "mango",
    name: "Mango",
    price: 30,
    desc: "This is a fresh Mango harvested just today. Grub yours fast.",
    img: "Images/mango.JPG",
  },
  {
    id: "potato",
    name: "Potato",
    price: 45,
    desc: "This is a fresh potato harvested just today. Grub yours fast.",
    img: "Images/potato.JPG",
  },
  {
    id: "banana",
    name: "Banana",
    price: 25,
    desc: "This is a fresh banana harvested just today. Grub yours fast.",
    img: "Images/banana.JPG",
  },
  {
    id: "potato",
    name: "Potato",
    price: 45,
    desc: "This is a fresh potato harvested just today. Grub yours fast.",
    img: "Images/potato.JPG",
  },
  {
    id: "greenApple",
    name: "Green Apple",
    price: 35,
    desc: "This is a fresh green apple harvested just today. Grub yours fast.",
    img: "Images/greenApple.JPG",
  },
  {
    id: "chikoo",
    name: "Chikoo",
    price: 45,
    desc: "This is a fresh chikoo harvested just today. Grub yours fast.",
    img: "Images/chikoo.JPG",
  },
  {
    id: "ladyFinger",
    name: "Lady Finger",
    price: 45,
    desc: "This is a fresh lady finger harvested just today. Grub yours fast.",
    img: "Images/ladyFinger.JPG",
  },
  {
    id: "masoor",
    name: "Masoor",
    price: 45,
    desc: "This is a fresh Masoor harvested just today. Grub yours fast.",
    img: "Images/masoor.JPG",
  },
  {
    id: "rice",
    name: "Rice",
    price: 45,
    desc: "This is a fresh Rice harvested just today. Grub yours fast.",
    img: "Images/rice.JPG",
  },
  {
    id: "mushroom",
    name: "Mushroom",
    price: 45,
    desc: "This is a fresh Mushroom harvested just today. Grub yours fast.",
    img: "Images/mushroom.JPG",
  },
];
